# This is a basic workflow for deploying azure resources using a bicep template file

name: github-actions-bicep-add-parameters&variables

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build-and-deploy:    
    runs-on: ubuntu-latest
    env:     
        ResourceGroupLocation: "australiaeast"
    
    steps:     
      - uses: actions/checkout@v3
          
      - name: Azure login
        uses: azure/login@v1.5.0
        with:
            creds: ${{ secrets.AZURE_CREDS }} # The creds is created maunally in azure and saved as a repo secret

      - name: create Resource group
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: | 
           #!/bin/bash
           az group create --name ${{ secrets.AZURE_AGAB_RG }} --location ${{env.ResourceGroupLocation}}
           echo "Azure resource group created"
             
      - name: deploy resources
        uses: azure/arm-deploy@v1
        with:
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # The subscriptionid was copied from Azure to the repository secret 
            resourceGroupName: ${{ secrets.AZURE_AGAB_RG }} # The resource group was created manually and the resource group name was added to the repo secret
            template: ./bicep/03-add-parameters&variables/main.bicep            
            failOnStdErr: false

